title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://alishokri1356E.github.io/Docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/alishokri1356/Docs
